#----------------------------------------------------------------------------------------------------------
# Alexa Text To Speech from MQTT
#----------------------------------------------------------------------------------------------------------

- alias: mqtt TTS
  initial_state: 'on'
  mode: queued
  max: 10
  trigger:
    - platform: mqtt
      topic: 'speak/#'
  action:
    - service: notify.alexa_media
      data_template:
        target: '{{ (trigger.topic).replace("speak/","media_player.").replace("media_player.basement ","media_player.thing_").replace("_tts","") }}'
        data:
          type: tts
        message: '{{trigger.payload}}'
    - service: persistent_notification.create
      data_template:
        message: |
          {{ trigger.payload }} 
          [{{ now().strftime("%Y-%m-%d %H:%M") }} {{ trigger.topic }}]
        title: "Spoken Message"

